name: Docker Image CI
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Build and push docker Image
        run: |
          docker build . -t abhigyan21/rest-demo:latest -f Dockerfile
          docker push abhigyan21/rest-demo:latest
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: kubernetes-cluster
          resource-group: kubernetes-resource-group
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.io
          container-registry-username: '${{ secrets.DOCKERHUB_USERNAME }}'
          container-registry-password: '${{ secrets.DOCKERHUB_PASSWORD }}'
          namespace: default
          force: true
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/rest-demo.yml
          images: |
            abhigyan21/rest-demo:latest
          namespace: default
          force: true
